#############################
#
# CONFIGURAÇÕES PARA O H2
#
#############################
server.port: 8082
spring:
  datasource:
    url: jdbc:h2:mem:oficina_db
    #url: jdbc:h2:file:./demo6
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    spring.jpa.defer-datasource-initialization: true
    properties.hibernate.format_sql: true
    properties.hibernate.show_sql: true
    spring.jpa.hibernate.ddl-auto: update
    #spring.jpa.hibernate.ddl-auto: create #Cria as tabelas
  h2: 
    console:
      enabled: true
      path: /h2
      settings: 
        trace: false
        web-allow-others: false
    
logging:
  level:
    org:
      hibernate:
        type: trace